### PR TITLE
add 20 new vanilla cards

### PR DESCRIPTION
**Pull request by deyemiobaa**
Hi Ryan. I added 20 new vanilla cards with this PR

### CODE REVIEW

**Review by radar — APPROVED** [review]
Looks great. Thank you.

**Comment by radar** [comment]
How would you like to be paid for this bounty?

**Comment by deyemiobaa** [comment]
I have a US bank account. It be transferred there via SWIFT

**Comment by radar** [comment]
image

Money transfer is handled through Wise. The email address you've made your commits with will receive an email from Wise shortly. Follow the instructions there to get your money. Thank you again for your contribution.

**Comment by deyemiobaa** [comment]
Thank you, Ryan. It's on its way!

**Comment by radar** [comment]
Hello again. I received an email from Wise saying that:

> There was a problem with the bank details we had for your USD account. 

Please email me@ryanbigg.com with your account details and I will attempt to manually update them using the form I have here. Here's what Wise is asking for:

image

**Pull request merged**
