### PR TITLE
add spec for rise again

### PR DESCRIPTION
**Pull request by afogel**
Hey,
So, as per our conversation in #497 , this is the added spec. I wasn't sure whether you it was necessary to cast the shock instant to send the creature to the graveyard, though I think either way the last action would still be rise again, so it wouldn't hit the second guard clause. I believe, effectively, this means that the containment priest's current implementation still functions as expected.

Let me know if I misunderstood or you'd like me to update the spec? Thanks!

### CODE REVIEW

**Comment by radar** [comment]
I've added a failing test here to demonstrate what I mean. Then realised I messed up by killing the Containment Priest. So now Wood Elves takes the Shock.

Current turn plays like:

1. P2 casts Rise Again, targeting the card in their graveyard
2. While this spell is on the stack, p2 casts Shock, targeting the Wood Elves.
3. `game.tick!` is called, which in this app resolves the stack.
4. `Shock` triggers first, dealing 2 damage to Wood Elves.
5. Rise Again triggers, but the creature should be sent to exile as P1's Containment Priest is still on the battlefield.

The last action to take place in the game here was P2's shock, not P2's Rise Again. Even though that was the last one to trigger.

So I think the `Actions::Cast` class needs to somehow flag that the card's resolution is happening _by way of a cast_ and that needs to stop the creature even entering the battlefield. So it's likely that `Card#resolve!` would need to check for these replacement effects before actually going about its resolution.

I'm currently unsure how to handle this correctly myself.

**Comment by afogel** [comment]
Ah, yeah, I see -- Sorcery, then Instant, which can mess up the existing logic. One idea I had was if there was a way to add the source, i.e. action, to the Event. That way, we'd be able to check to understand how an event was triggered and implement the logic without relying on assumption about action order? What do you think?

**Comment by radar** [comment]
Yes, that's one way to handle it. I think we will need a `WillEnterTheBattlefield` event that can be replaced, as Containment Priest is a Replacement Effect ability. 

What I think needs to happen is:

1. `Permanent.resolve!` issues a `Events::WillEnterTheBattlefield` event.
2. The system needs to check if any existing card on the board has a replacement effect for this (check how Nine Lives handles this already)
3. If there is a replacement effect, then that replacement effect takes place.
4. If there is no replacement effect, then the current resolution steps of moving it from a zone onto the battlefield take place.

**Comment by radar** [comment]
I've been able to fix this now, by putting a `cast` indicator on `Permanent.resolve`.

**Pull request merged**
